//***********************************************************************************
// Include files
//***********************************************************************************
#include "Cryotimer.h"
#include "em_cryotimer.h"
//***********************************************************************************
// defined files
//***********************************************************************************


//***********************************************************************************
// global variables
//***********************************************************************************


//***********************************************************************************
// function prototypes
//***********************************************************************************
//***********************************************************************************
// cryotimer_initialize will initialize the cryotimer to be used for the capacitive sensor
// When enabling the cryotimer we set the oscillator to the ULFRCO as the period to 1 sec
// After the cryotimer has been initialized the interrupt flag for when a periodic interrupts is
// enabled.
// the function takes no inputs and returns no outputs
//***********************************************************************************
void cryotimer_initialize(void)
{
	CRYOTIMER_Init_TypeDef My_Cryo;

	My_Cryo.osc = cryotimerOscULFRCO;
	My_Cryo.period = cryotimerPeriod_1k;
	My_Cryo.presc = cryotimerPresc_1;
	My_Cryo.em4Wakeup = false;
	My_Cryo.enable = false;
	My_Cryo.debugRun = false;

	CRYOTIMER_Init(&My_Cryo);

	CRYOTIMER->IFC = CRYOTIMER_IFC_PERIOD;
	CRYOTIMER_IntEnable(CRYOTIMER_IEN_PERIOD);

	NVIC_EnableIRQ(CRYOTIMER_IRQn);
}
//***********************************************************************************
// The cryotimer interrupt handler is triggered once every sec
// every time the cryotimer generates an interrupt and checks to see if the interrupt was caused by the time lapse of a single period
// if the interrupt was generated by the end of a period then the code set up the scheduler to check for a button press on the capacitive sensor
// the function takes no inputs and returns no outputs
//***********************************************************************************
void CRYOTIMER_IRQHandler(void)
{
	CORE_ATOMIC_IRQ_DISABLE();

	uint32_t interrupt_cause;

	interrupt_cause = CRYOTIMER->IF;

	CRYOTIMER->IFC = interrupt_cause;

	if(interrupt_cause & CRYOTIMER_IFC_PERIOD)
	{
		Scheduler |= Cryo_event;
	}
	CORE_ATOMIC_IRQ_ENABLE();
}
